// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nav-redesign/NavAfter.tsx": () => import("../components/mockups/nav-redesign/NavAfter.tsx"),
  "./components/mockups/nav-redesign/NavBefore.tsx": () => import("../components/mockups/nav-redesign/NavBefore.tsx"),
  "./components/mockups/upload-redesign/ClarityFirst.tsx": () => import("../components/mockups/upload-redesign/ClarityFirst.tsx"),
  "./components/mockups/upload-redesign/WorkflowGuided.tsx": () => import("../components/mockups/upload-redesign/WorkflowGuided.tsx")
};
